apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
   path: /home/banshaotuan/nfs/volumes/data/mysql
   server: 10.24.12.3

